### ISSUE TITLE
Can't clear storage for a conversation

### ISSUE THREAD

**Issue by cedricfung** [MixinNetwork/android-app#1409]
**Describe the bug**
Clear storage for a conversation with a large usage(7GB) will run forever.

**Smartphone (please complete the following information):**
 - Device: Galaxy S10
 - OS: Android 10
 - Version 0.24.10

**Comment by SeniorZhai** [comment]
The current file management solution is only related to the message, so when cleaning the files, the files will be deleted one by one according to the message. If you delete too many files, it will be very slow.
We will adopt a new management [solution](https://github.com/MixinNetwork/android-app/pull/1226), each conversation will have its own file directory, will solve this problem.
