### ISSUE TITLE
Android 11 features support 

### ISSUE THREAD

**Issue by crossle** [MixinNetwork/android-app#1663]
* Conversation notifications appear in a dedicated section at the top of the shade, with a people-forward design and conversation specific actions, such as opening the conversation as a bubble, creating a conversation shortcut on the home screen, or setting a reminder.
* Bubbles - Bubbles help users keep conversations in view and accessible while multitasking on their devices. Messaging and chat apps should use the Bubbles API on notifications to enable this in Android 11.
* Sharing shortcuts (from Android 10) - Apps that want to receive shared data should use the sharing shortcuts APIs to create share targets. Apps that want to send shared data should make sure to use the system share sheet.

https://android-developers.googleblog.com/2020/09/android11-final-release.html

**Comment by Tougee** [comment]
https://github.com/MixinNetwork/android-app/pull/2723
