### ISSUE TITLE
Fallback map for Location

### ISSUE THREAD

**Issue by crossle** [MixinNetwork/android-app#1667]
Some phones no Google Map, we should fallback to another map.

https://www.mapbox.com/
https://www.openstreetmap.org/

**Comment by crossle** [comment]
https://developer.apple.com/documentation/mapkitjs

**Comment by Tougee** [comment]
https://github.com/MixinNetwork/android-app/pull/2188

**Comment by crossle** [comment]
Maplibre.org Open Maps SDKs for web and mobile: community driven Mapbox GL fork https://maplibre.org/
