### ISSUE TITLE
signal protocol ---- sessionId

### ISSUE THREAD

**Issue by Pacyx** [MixinNetwork/android-app#1673]
在您的项目中，对于加密这一块， session_id 是做什么的，如何生成的，您在用户登录的时候，获取自己的session_id , 创建会话的时候，拿到对方的sesison_id ， 加密的还是传入这个，和通过session_id 生成devices_id ，这个session_id是会改变的，望解答，🙏

**Comment by crossle** [comment]
就是一个设备唯一的一个 🆔。
