### ISSUE TITLE
通过scheme打开mixin客户端异常

### ISSUE THREAD

**Issue by firefly1126** [MixinNetwork/android-app#173]
### Step 2: Describe your environment

  * Device: _____OnePlus 3T
  * OS version: _____android 8.0.0
  * App version: _____0.6.0
  
### Step 3: Describe the problem:
通过sheme打开mixin客户端异常，打开的是一个透明页面，只看到系统的status bar发生变化
#### Steps to reproduce:

  1. _____在第三方app里面通过scheme `mixin://users/7000101276`打开mixin客户端
  2. _____吊起mixin app页面
  3. _____出现透明页面
  
#### Expected Results:

  * 期望通过不同的scheme能吊起相应的功能页面

**Comment by crossle** [comment]
请用最新的版本 0.6.5
