### ISSUE TITLE
BUG: 钱包里面数字货币显示比例有错

### ISSUE THREAD

**Issue by firefly1126** [MixinNetwork/android-app#188]
![wechatimg256](https://user-images.githubusercontent.com/3377613/44827810-6d3a6880-ac47-11e8-97d7-22903f37d02c.jpeg)

**Comment by firefly1126** [comment]
XIN 和 PRS都显示为 100%

**Comment by Tougee** [comment]
是什么版本的

**Comment by crossle** [comment]
Fixed
