### ISSUE TITLE
Please update Bouncy Castle

### ISSUE THREAD

**Issue by Neustradamus** [MixinNetwork/android-app#1978]
Please update Bouncy Castle
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by crossle** [comment]
https://github.com/MixinNetwork/android-app/commit/be6c592f1aca584b91b6e81eb1224aa1b4db8447

**Comment by Neustradamus** [comment]
@crossle: Removed?

There is always:
- https://github.com/MixinNetwork/android-app/search?q=bouncycastle&type=

**Comment by Neustradamus** [comment]
And in the organization:
- https://github.com/search?q=org%3AMixinNetwork+bouncycastle&type=code

**Comment by crossle** [comment]
Thanks for your remind, we will remove all Bouncy castle dependence, replace with https://github.com/google/conscrypt

**Comment by Tougee** [comment]
https://github.com/MixinNetwork/android-app/pull/2615
https://github.com/MixinNetwork/bot-api-kotlin-client/commit/4ccd44872a75e01bc15e8dd29a94a1f8c2c61766

Upgrade to the latest version now, migrating to `conscrypt` can be considered later.
