### ISSUE TITLE
Remove JCenter lines from build.gradle or at least specify what used by it directly

### ISSUE THREAD

**Issue by emanuelb** [MixinNetwork/android-app#2489]
https://github.com/MixinNetwork/android-app/blob/4da5de33920b8052cadd8edad18b50a3a91a0f2b/build.gradle#L110
https://github.com/MixinNetwork/android-app/blob/4da5de33920b8052cadd8edad18b50a3a91a0f2b/build.gradle#L127

Jcenter service is closed (currently in read-only mode, no updates for packages will be made)
more details on needed migration:
https://developer.android.com/studio/build/jcenter-migration
https://blog.gradle.org/jcenter-shutdown

and here content on how to migrate:
https://jeroenmols.com/blog/2021/02/04/migratingjcenter/

You can declare specific usages of jcenter like explained in https://jeroenmols.com/blog/2021/02/04/migratingjcenter/#consumed-dependencies-from-bintrayjcenter and like it's done for example in this PR of unstoppable wallet "Gradually migrate from jcenter to mavenCentral"
https://github.com/horizontalsystems/unstoppable-wallet-android/pull/3752/files

**Comment by crossle** [comment]
Fixed
