### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by emanuelb** [MixinNetwork/android-app#2490]
This repo don't contain instructions to build the app and what deps are required, looks like JDK > 11 is needed, also adding `MAPBOX_DOWNLOADS_TOKEN=PASTE_YOUR_SECRET_TOKEN_HERE`
to `gradle.properties` file is needed, otherwise mapbox return "Unauthorized" error, when tried to compile the app, as can be seen at:
https://gitlab.com/walletscrutiny/walletScrutinyCom/-/issues/344#note_683241277

**Comment by Tougee** [comment]
We recently changed to JDK 11 https://github.com/MixinNetwork/android-app/commit/5c4238fad103efda0e8dbc1e1eece4558df8d920
