### ISSUE TITLE
Upgrade NDK to supported version

### ISSUE THREAD

**Issue by emanuelb** [MixinNetwork/android-app#2506]
The NDK version used is "21.3.6528147"
https://github.com/MixinNetwork/android-app/blob/8c4a2539f979b1fadb42e4b7d6cb9d0220ace050/app/build.gradle#L16

is downloaded from page "Unsupported Downloads" (the "21e")
https://github.com/android/ndk/wiki/Unsupported-Downloads#r21e

> Note: these obsolete versions of the NDK are no longer supported. Use a current release instead.

pages that show supported versions are which is "23.0.7599858"
https://developer.android.com/ndk/downloads/#older-downloads
https://github.com/android/ndk/wiki

**Comment by crossle** [comment]
Fixed https://github.com/MixinNetwork/android-app/commit/22e79ea5b4392b894182259a5a0b978d742b0de1
