### ISSUE TITLE
Cannot withdraw to a BNB address without a Memo

### ISSUE THREAD

**Issue by christian-oudard** [MixinNetwork/android-app#2594]
**Describe the bug**
When attempting to withdraw to a BNB address, and selecting "No Memo", it disallows this, giving an error about the memo format.

**To Reproduce**
1. Add a BNB address
2. Type in a valid bnb address code. 
3. Select "No Memo"
4. Press "Save"
4. See error message

**Expected behavior**
The address is added

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Latest Android
 - Version: Mixin messenger 0.32.8

**Comment by crossle** [comment]
If no require, please input any number as memo

**Comment by crossle** [comment]
@christian-oudard Do you withdrawal success?
