### ISSUE TITLE
Show wallet after scan user's profile QrCode

### ISSUE THREAD

**Issue by lyricat** [MixinNetwork/android-app#347]
* Device: RedMi 5
  * OS version: MIUI 9.6/Android 7.1.2
  * App version:  0.10.2

#### Steps to reproduce:

1. Create a new user with on contacts.
2. Sign in
3. Scan another user's Profile QrCode

#### Observed Results:

Switch to wallet view.
  
#### Expected Results:

Show the user's profile.

Code: https://github.com/MixinNetwork/android-app/blob/master/app/src/main/java/one/mixin/android/ui/home/ConversationListFragment.kt#L146

**Comment by Tougee** [comment]
Fixed by https://github.com/MixinNetwork/android-app/pull/348
